import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SmoothScroll from "@/components/smoothscroll";

const ppacmaBook = localFont({
  src: "./fonts/PPAcma-Book.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ppacmaBook.className} antialiased`}>
        {children}
        <SmoothScroll />
      </body>
    </html>
  );
}
